/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Asset {
    id: bigint;
    status: string;
    clearanceLevel: bigint;
    name: string;
    description: string;
    assetType: string;
    department: string;
}
export interface Agent {
    id: bigint;
    bio: string;
    status: AgentStatus;
    clearanceLevel: bigint;
    name: string;
    rank: string;
    codename: string;
    officerTitle: string;
    department: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MostWanted {
    id: bigint;
    status: string;
    alias: string;
    threatLevel: string;
    lastKnownLocation: string;
    name: string;
    charges: string;
}
export interface Mission {
    id: bigint;
    status: string;
    title: string;
    classificationLevel: string;
    date: string;
    description: string;
    department: string;
    assignedAgents: Array<bigint>;
}
export enum AgentStatus {
    Inactive = "Inactive",
    Active = "Active",
    Banned = "Banned",
    Kicked = "Kicked",
    Redacted = "Redacted"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    banAgent(id: bigint): Promise<void>;
    createAgent(name: string, codename: string, department: string, rank: string, officerTitle: string, status: AgentStatus, bio: string, clearanceLevel: bigint): Promise<bigint>;
    createAsset(name: string, assetType: string, department: string, status: string, description: string, clearanceLevel: bigint): Promise<bigint>;
    createMission(title: string, department: string, classificationLevel: string, status: string, description: string, assignedAgents: Array<bigint>, date: string): Promise<bigint>;
    createMostWanted(name: string, alias: string, threatLevel: string, lastKnownLocation: string, charges: string, status: string): Promise<bigint>;
    deleteAsset(id: bigint): Promise<void>;
    deleteMission(id: bigint): Promise<void>;
    deleteMostWanted(id: bigint): Promise<void>;
    getAgent(id: bigint): Promise<Agent>;
    getAllAgents(): Promise<Array<Agent>>;
    getAllAssets(): Promise<Array<Asset>>;
    getAllMissions(): Promise<Array<Mission>>;
    getAllMostWanted(): Promise<Array<MostWanted>>;
    getAsset(id: bigint): Promise<Asset>;
    getMission(id: bigint): Promise<Mission>;
    getMostWanted(id: bigint): Promise<MostWanted>;
    removeAgent(id: bigint): Promise<void>;
    updateAgent(id: bigint, name: string, codename: string, department: string, rank: string, officerTitle: string, status: AgentStatus, bio: string, clearanceLevel: bigint): Promise<void>;
    updateAsset(id: bigint, name: string, assetType: string, department: string, status: string, description: string, clearanceLevel: bigint): Promise<void>;
    updateMission(id: bigint, title: string, department: string, classificationLevel: string, status: string, description: string, assignedAgents: Array<bigint>, date: string): Promise<void>;
    updateMostWanted(id: bigint, name: string, alias: string, threatLevel: string, lastKnownLocation: string, charges: string, status: string): Promise<void>;
}
import type { Agent as _Agent, AgentStatus as _AgentStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async banAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banAgent(arg0);
            return result;
        }
    }
    async createAgent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: AgentStatus, arg6: string, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgent(arg0, arg1, arg2, arg3, arg4, to_candid_AgentStatus_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgent(arg0, arg1, arg2, arg3, arg4, to_candid_AgentStatus_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async createAsset(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAsset(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAsset(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createMission(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<bigint>, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMission(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMission(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createMostWanted(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMostWanted(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMostWanted(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteMission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMission(arg0);
            return result;
        }
    }
    async deleteMostWanted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMostWanted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMostWanted(arg0);
            return result;
        }
    }
    async getAgent(arg0: bigint): Promise<Agent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_Agent_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_Agent_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return result;
        }
    }
    async getAllMissions(): Promise<Array<Mission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMissions();
            return result;
        }
    }
    async getAllMostWanted(): Promise<Array<MostWanted>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMostWanted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMostWanted();
            return result;
        }
    }
    async getAsset(arg0: bigint): Promise<Asset> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return result;
        }
    }
    async getMission(arg0: bigint): Promise<Mission> {
        if (this.processError) {
            try {
                const result = await this.actor.getMission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMission(arg0);
            return result;
        }
    }
    async getMostWanted(arg0: bigint): Promise<MostWanted> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostWanted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostWanted(arg0);
            return result;
        }
    }
    async removeAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAgent(arg0);
            return result;
        }
    }
    async updateAgent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: AgentStatus, arg7: string, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AgentStatus_n8(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AgentStatus_n8(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async updateAsset(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateMission(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<bigint>, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMission(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMission(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateMostWanted(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMostWanted(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMostWanted(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_AgentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Agent_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    status: _AgentStatus;
    clearanceLevel: bigint;
    name: string;
    rank: string;
    codename: string;
    officerTitle: string;
    department: string;
}): {
    id: bigint;
    bio: string;
    status: AgentStatus;
    clearanceLevel: bigint;
    name: string;
    rank: string;
    codename: string;
    officerTitle: string;
    department: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        status: from_candid_AgentStatus_n12(_uploadFile, _downloadFile, value.status),
        clearanceLevel: value.clearanceLevel,
        name: value.name,
        rank: value.rank,
        codename: value.codename,
        officerTitle: value.officerTitle,
        department: value.department
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Banned: null;
} | {
    Kicked: null;
} | {
    Redacted: null;
}): AgentStatus {
    return "Inactive" in value ? AgentStatus.Inactive : "Active" in value ? AgentStatus.Active : "Banned" in value ? AgentStatus.Banned : "Kicked" in value ? AgentStatus.Kicked : "Redacted" in value ? AgentStatus.Redacted : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AgentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): _AgentStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    Banned: null;
} | {
    Kicked: null;
} | {
    Redacted: null;
} {
    return value == AgentStatus.Inactive ? {
        Inactive: null
    } : value == AgentStatus.Active ? {
        Active: null
    } : value == AgentStatus.Banned ? {
        Banned: null
    } : value == AgentStatus.Kicked ? {
        Kicked: null
    } : value == AgentStatus.Redacted ? {
        Redacted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
