/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : bigint,
  'bio' : string,
  'status' : AgentStatus,
  'clearanceLevel' : bigint,
  'name' : string,
  'rank' : string,
  'codename' : string,
  'officerTitle' : string,
  'department' : string,
}
export type AgentStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Banned' : null } |
  { 'Kicked' : null } |
  { 'Redacted' : null };
export interface Asset {
  'id' : bigint,
  'status' : string,
  'clearanceLevel' : bigint,
  'name' : string,
  'description' : string,
  'assetType' : string,
  'department' : string,
}
export interface Mission {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'classificationLevel' : string,
  'date' : string,
  'description' : string,
  'department' : string,
  'assignedAgents' : Array<bigint>,
}
export interface MostWanted {
  'id' : bigint,
  'status' : string,
  'alias' : string,
  'threatLevel' : string,
  'lastKnownLocation' : string,
  'name' : string,
  'charges' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Weapon {
  'id' : bigint,
  'status' : string,
  'clearanceLevel' : bigint,
  'name' : string,
  'description' : string,
  'weaponType' : string,
  'department' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banAgent' : ActorMethod<[bigint], undefined>,
  'createAgent' : ActorMethod<
    [string, string, string, string, string, AgentStatus, string, bigint],
    bigint
  >,
  'createAsset' : ActorMethod<
    [string, string, string, string, string, bigint],
    bigint
  >,
  'createMission' : ActorMethod<
    [string, string, string, string, string, Array<bigint>, string],
    bigint
  >,
  'createMostWanted' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'createWeapon' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'deleteMission' : ActorMethod<[bigint], undefined>,
  'deleteMostWanted' : ActorMethod<[bigint], undefined>,
  'deleteWeapon' : ActorMethod<[bigint], undefined>,
  'getAgent' : ActorMethod<[bigint], Agent>,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAllMissions' : ActorMethod<[], Array<Mission>>,
  'getAllMostWanted' : ActorMethod<[], Array<MostWanted>>,
  'getAsset' : ActorMethod<[bigint], Asset>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMission' : ActorMethod<[bigint], Mission>,
  'getMostWanted' : ActorMethod<[bigint], MostWanted>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeapons' : ActorMethod<[], Array<Weapon>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAgent' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAgent' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      AgentStatus,
      string,
      bigint,
    ],
    undefined
  >,
  'updateAsset' : ActorMethod<
    [bigint, string, string, string, string, string, bigint],
    undefined
  >,
  'updateMission' : ActorMethod<
    [bigint, string, string, string, string, string, Array<bigint>, string],
    undefined
  >,
  'updateMostWanted' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
  'updateWeapon' : ActorMethod<
    [bigint, string, string, string, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];