/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AgentStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Banned' : IDL.Null,
  'Kicked' : IDL.Null,
  'Redacted' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'status' : AgentStatus,
  'clearanceLevel' : IDL.Nat,
  'name' : IDL.Text,
  'rank' : IDL.Text,
  'codename' : IDL.Text,
  'officerTitle' : IDL.Text,
  'department' : IDL.Text,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clearanceLevel' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'assetType' : IDL.Text,
  'department' : IDL.Text,
});
export const Mission = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'classificationLevel' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'department' : IDL.Text,
  'assignedAgents' : IDL.Vec(IDL.Nat),
});
export const MostWanted = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'alias' : IDL.Text,
  'threatLevel' : IDL.Text,
  'lastKnownLocation' : IDL.Text,
  'name' : IDL.Text,
  'charges' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'banAgent' : IDL.Func([IDL.Nat], [], []),
  'createAgent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AgentStatus,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createMission' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createMostWanted' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'deleteMission' : IDL.Func([IDL.Nat], [], []),
  'deleteMostWanted' : IDL.Func([IDL.Nat], [], []),
  'getAgent' : IDL.Func([IDL.Nat], [Agent], ['query']),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getAllMostWanted' : IDL.Func([], [IDL.Vec(MostWanted)], ['query']),
  'getAsset' : IDL.Func([IDL.Nat], [Asset], ['query']),
  'getMission' : IDL.Func([IDL.Nat], [Mission], ['query']),
  'getMostWanted' : IDL.Func([IDL.Nat], [MostWanted], ['query']),
  'removeAgent' : IDL.Func([IDL.Nat], [], []),
  'updateAgent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AgentStatus,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateAsset' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateMission' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateMostWanted' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AgentStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Banned' : IDL.Null,
    'Kicked' : IDL.Null,
    'Redacted' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'status' : AgentStatus,
    'clearanceLevel' : IDL.Nat,
    'name' : IDL.Text,
    'rank' : IDL.Text,
    'codename' : IDL.Text,
    'officerTitle' : IDL.Text,
    'department' : IDL.Text,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clearanceLevel' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'assetType' : IDL.Text,
    'department' : IDL.Text,
  });
  const Mission = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'classificationLevel' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'department' : IDL.Text,
    'assignedAgents' : IDL.Vec(IDL.Nat),
  });
  const MostWanted = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'alias' : IDL.Text,
    'threatLevel' : IDL.Text,
    'lastKnownLocation' : IDL.Text,
    'name' : IDL.Text,
    'charges' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'banAgent' : IDL.Func([IDL.Nat], [], []),
    'createAgent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AgentStatus,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createMission' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createMostWanted' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'deleteMission' : IDL.Func([IDL.Nat], [], []),
    'deleteMostWanted' : IDL.Func([IDL.Nat], [], []),
    'getAgent' : IDL.Func([IDL.Nat], [Agent], ['query']),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getAllMostWanted' : IDL.Func([], [IDL.Vec(MostWanted)], ['query']),
    'getAsset' : IDL.Func([IDL.Nat], [Asset], ['query']),
    'getMission' : IDL.Func([IDL.Nat], [Mission], ['query']),
    'getMostWanted' : IDL.Func([IDL.Nat], [MostWanted], ['query']),
    'removeAgent' : IDL.Func([IDL.Nat], [], []),
    'updateAgent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AgentStatus,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateAsset' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateMission' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateMostWanted' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };